name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          cache: true
          deno-version: 2.9.1

      - name: Build
        run: "deno task build"
