name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: 2.9.0

      - name: Deploy
        run: deno task deploy

  purge-cache:
    needs: deploy
    name: Purge cache
    uses: ./.github/workflows/purge-cache.yml
    secrets: inherit
