name: Purge cache

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  purge-cache:
    name: Purge cache
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@f98bb26551cd1af7d3eb2674578a80754ece88db # v2.0.1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache"
          method: "POST"
          bearerToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          data: '{ "purge_everything": true }'
          retry: 3
